# Generated by Django 4.1.7 on 2023-03-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
