# Generated by Django 4.1.7 on 2023-03-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login1',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='data',
            name='asignto',
        ),
        migrations.RemoveField(
            model_name='data',
            name='review',
        ),
        migrations.RemoveField(
            model_name='data',
            name='status',
        ),
        migrations.RemoveField(
            model_name='data',
            name='task',
        ),
    ]
