# Generated by Django 4.1.7 on 2023-03-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_login1_rename_name_data_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='option',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
