# Generated by Django 4.1.7 on 2023-03-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
